/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

open class MesgFilter: MesgSource, MesgListener {
    public private(set)var mesgListeners = [ObjectIdentifier : MesgListener]()

    public init() {}

    open func addMesgListener(_ listener: MesgListener) {
        let id = ObjectIdentifier(listener)
        mesgListeners[id] = listener
    }

    open func removeMesgListener(_ listener: MesgListener) {
        let id = ObjectIdentifier(listener)
        mesgListeners.removeValue(forKey: id)
    }

    open func onMesg(_ mesg: Mesg) throws {
        for mesgListener in mesgListeners.values {
            try mesgListener.onMesg(mesg)
        }
    }
}
