/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum BacklightMode: UInt8, CaseIterable, Sendable {
    case off = 0
    case manual = 1
    case keyAndMessages = 2
    case autoBrightness = 3
    case smartNotifications = 4
    case keyAndMessagesNight = 5
    case keyAndMessagesAndSmartNotifications = 6
    case invalid = 0xFF
}
