/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum BatteryStatus: UInt8, CaseIterable, Sendable {
    case new = 1
    case good = 2
    case ok = 3
    case low = 4
    case critical = 5
    case charging = 6
    case unknown = 7
    case invalid = 0xFF
}
