/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum BpStatus: UInt8, CaseIterable, Sendable {
    case noError = 0
    case errorIncompleteData = 1
    case errorNoMeasurement = 2
    case errorDataOutOfRange = 3
    case errorIrregularHeartRate = 4
    case invalid = 0xFF
}
