/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum EventType: UInt8, CaseIterable, Sendable {
    case start = 0
    case stop = 1
    case consecutiveDepreciated = 2
    case marker = 3
    case stopAll = 4
    case beginDepreciated = 5
    case endDepreciated = 6
    case endAllDepreciated = 7
    case stopDisable = 8
    case stopDisableAll = 9
    case invalid = 0xFF
}
