/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum ExdLayout: UInt8, CaseIterable, Sendable {
    case fullScreen = 0
    case halfVertical = 1
    case halfHorizontal = 2
    case halfVerticalRightSplit = 3
    case halfHorizontalBottomSplit = 4
    case fullQuarterSplit = 5
    case halfVerticalLeftSplit = 6
    case halfHorizontalTopSplit = 7
    case dynamic = 8
    case invalid = 0xFF
}
