/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias LanguageBits0 = UInt8

public struct LanguageBits0Values: Sendable {
    public static let english: LanguageBits0 = 0x01
    public static let french: LanguageBits0 = 0x02
    public static let italian: LanguageBits0 = 0x04
    public static let german: LanguageBits0 = 0x08
    public static let spanish: LanguageBits0 = 0x10
    public static let croatian: LanguageBits0 = 0x20
    public static let czech: LanguageBits0 = 0x40
    public static let danish: LanguageBits0 = 0x80
    public static let invalid = 0x00
}
