/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias LeftRightBalance100 = UInt16

public struct LeftRightBalance100Values: Sendable {
    public static let mask: LeftRightBalance100 = 0x3FFF
    public static let right: LeftRightBalance100 = 0x8000
    public static let invalid = 0xFFFF
}
