/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum LegCurlExerciseName: UInt16, CaseIterable, Sendable {
    case legCurl = 0
    case weightedLegCurl = 1
    case goodMorning = 2
    case seatedBarbellGoodMorning = 3
    case singleLegBarbellGoodMorning = 4
    case singleLegSlidingLegCurl = 5
    case slidingLegCurl = 6
    case splitBarbellGoodMorning = 7
    case splitStanceExtension = 8
    case staggeredStanceGoodMorning = 9
    case swissBallHipRaiseAndLegCurl = 10
    case zercherGoodMorning = 11
    case bandGoodMorning = 12
    case barGoodMorning = 13
    case invalid = 0xFFFF
}
