/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum LocalDeviceType: UInt8, CaseIterable, Sendable {
    case gps = 0
    case glonass = 1
    case gpsGlonass = 2
    case accelerometer = 3
    case barometer = 4
    case temperature = 5
    case whr = 10
    case sensorHub = 12
    case invalid = 0xFF
}
