/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SegmentLeaderboardType: UInt8, CaseIterable, Sendable {
    case overall = 0
    case personalBest = 1
    case connections = 2
    case group = 3
    case challenger = 4
    case kom = 5
    case qom = 6
    case pr = 7
    case goal = 8
    case carrot = 9
    case clubLeader = 10
    case rival = 11
    case last = 12
    case recentBest = 13
    case courseRecord = 14
    case invalid = 0xFF
}
