/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SensorType: UInt8, CaseIterable, Sendable {
    case accelerometer = 0
    case gyroscope = 1
    case compass = 2
    case barometer = 3
    case invalid = 0xFF
}
