/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SwimStroke: UInt8, CaseIterable, Sendable {
    case freestyle = 0
    case backstroke = 1
    case breaststroke = 2
    case butterfly = 3
    case drill = 4
    case mixed = 5
    case im = 6
    case imByRound = 7
    case rimo = 8
    case invalid = 0xFF
}
